ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "rating" INTEGER NOT NULL DEFAULT 1000;

ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "ratingBefore" INTEGER;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "ratingAfter" INTEGER;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "ratingDelta" INTEGER;

CREATE INDEX IF NOT EXISTS "Game_ratingDelta_idx" ON "Game"("ratingDelta");
